#define FUNCNAME_nulcmd 0
#define FUNCNAME_quitfm 1
#define FUNCNAME_adBmark 2
#define FUNCNAME_backBf 3
#define FUNCNAME_goLineF 4
#define FUNCNAME_ldBmark 5
#define FUNCNAME_ctrCsrH 6
#define FUNCNAME_ctrCsrV 7
#define FUNCNAME_cooLst 8
#define FUNCNAME_deletePrevBuf 9
#define FUNCNAME_dictword 10
#define FUNCNAME_dictwordat 11
#define FUNCNAME_ldown1 12
#define FUNCNAME_svSrc 13
#define FUNCNAME_editBf 14
#define FUNCNAME_editScr 15
#define FUNCNAME_goLineL 16
#define FUNCNAME_escbmap 17
#define FUNCNAME_escmap 18
#define FUNCNAME_execsh 19
#define FUNCNAME_extbrz 21
#define FUNCNAME_linkbrz 22
#define FUNCNAME_rFrame 23
#define FUNCNAME_goURL 24
#define FUNCNAME_goLine 25
#define FUNCNAME_followA 26
#define FUNCNAME_ldhelp 27
#define FUNCNAME_ldHist 28
#define FUNCNAME_pginfo 29
#define FUNCNAME_initMailcap 30
#define FUNCNAME_susp 31
#define FUNCNAME_col1L 32
#define FUNCNAME_linbeg 33
#define FUNCNAME_linend 34
#define FUNCNAME_curlno 35
#define FUNCNAME_topA 36
#define FUNCNAME_lastA 37
#define FUNCNAME_ldfile 38
#define FUNCNAME_mainMn 39
#define FUNCNAME__mark 40
#define FUNCNAME_chkNMID 41
#define FUNCNAME_chkURL 42
#define FUNCNAME_mouse 44
#define FUNCNAME_msToggle 45
#define FUNCNAME_movD 46
#define FUNCNAME_movL 47
#define FUNCNAME_movR 48
#define FUNCNAME_movU 49
#define FUNCNAME_msgs 50
#define FUNCNAME_nextA 51
#define FUNCNAME_nextMk 52
#define FUNCNAME_pgFore 53
#define FUNCNAME_movRW 54
#define FUNCNAME_ldOpt 57
#define FUNCNAME_pcmap 58
#define FUNCNAME_curURL 59
#define FUNCNAME_peekURL 60
#define FUNCNAME_peekIMG 61
#define FUNCNAME_pipesh 62
#define FUNCNAME_prevA 63
#define FUNCNAME_prevMk 64
#define FUNCNAME_pgBack 65
#define FUNCNAME_movLW 66
#define FUNCNAME_svBuf 67
#define FUNCNAME_qquitfm 68
#define FUNCNAME_readsh 69
#define FUNCNAME_rdrwSc 70
#define FUNCNAME_reMark 71
#define FUNCNAME_reload 72
#define FUNCNAME_col1R 73
#define FUNCNAME_svI 75
#define FUNCNAME_svA 76
#define FUNCNAME_srchfor 78
#define FUNCNAME_srchbak 79
#define FUNCNAME_srchnxt 81
#define FUNCNAME_srchprv 82
#define FUNCNAME_selBuf 83
#define FUNCNAME_shiftl 85
#define FUNCNAME_shiftr 86
#define FUNCNAME_vwSrc 87
#define FUNCNAME_lup1 89
#define FUNCNAME_followI 92
#define FUNCNAME_wrapToggle 94
