#!/bin/sh
CODE=-code=S
for arg in $*
do
    case $arg in
    -code=*)
        CODE=$arg
        ;;
    esac
done
for model in baby little mouse cookie
do 
    for lang in ja en
    do 
        sh configure -yes -model=$model -lang=$lang -cflags=-O $CODE
        make clean
        make
        make bindist
    done
done
