.\"
.TH W3M 1 "Jun 6 2000" "UNIX"
.SH NAME
.B w3m
\- text base pager/WWW browser
.SH SYNOPSYS
.B w3m
[options] [file | URL]
.SH DESCRIPTION
.SS はじめに
.B w3m
は，テキストベースのページャ/WWWブラウザです．これを使うと，
.I kterm\fR(1)
などのキャラクタ端末上で，ローカルファイルを見たり，WWWの内容を見たりすること
ができます．
.PP
引数にファイル名を指定すればそのファイルを表示し，URLを指定すればその内容を表
示します．何も指定しなければ，標準入力の内容を表示します．ただし，標準入力が
.I tty\fR(4)
である場合には，何もせずに終了します．
.PP
オプションは次の通りです．
.TP
.BI + 番号
起動後，指定の行番号に移動する．
.TP
.BI \-t\  幅
タブの幅を指定する．デフォルトは 8．
.TP
.B \-r
text/plainの文書を表示する場合，重ね打ちによる強調文字を表示しない．
このオプションを付けない場合，
``A^H_''
はAのアンダーラインとして表示され，
``A^HA''
はAのボールドとして表示される．
.TP
.BI \-l\  行数
標準入力の内容を表示するときに保存される最大行数を指定する．
デフォルトは10000．
.TP
.B \-s
Shift_JISコードで表示する．
.TP
.B \-e
EUCコードで表示する．
.TP
.B \-j
JIS (ISO-2022-JP)コードで表示する．
.TP
.BI \-O\  e|s|j|N|m
表示に使う文字コードを指定する.
.TP
.BI \-I\  e|s
入力文書の文字コードを指定する．
.TP
.BI \-T\  タイプ
表示する文書のタイプを指定する．この指定がない場合，ファイル名の拡張子によって
自動判別される．判別できない場合はtext/plainとみなされる．
.PP
.RS
.B 例：
.TP
cat hoge*.html | w3m -T text/html
標準入力からHTMLファイルを読んで表示する
.TP
w3m -T text/plain hoge*.html
HTMLファイルのソースを表示する
.RE
.TP
.B \-m
Internet messageモードで表示する．Internet messageモードの場合，
ヘッダの内容を見て，Content-Type: があればそれを参考にする．電子メールや
ネットニュースの記事を読むときに便利．
.TP
.B \-v
visual startupモード．
コマンドライン引数に URL やファイルを指定していなくても
初期画面が表示される.
.TP
.B \-B
Bookmarkを表示する．
.TP
.BI \-bookmark\  file
Bookmark のファイルを指定する．
.TP
.B \-M
カラー表示をしない．
.TP
.B \-F
フレームを自動表示する．
.TP
.B \-S
連続する空行を1行にまとめて表示する．
.TP
.B \-X
.B w3m
終了時に，以前の画面に戻らない．
.TP
.BI \-title =TERM
端末のタイトル文字列を設定する.
.TP
.B \-W
折り返しサーチを使うかどうかを切りかえる．
.TP
.BI \-o\  option=value
オプションを指定する．
.TP
.B \-show-option
利用できるオプションを表示する.
.TP
.B \-no\-proxy
プロキシを利用しない．
.TP
.BI \-pauth\  user:pass
プロキシ認証用のユーザ名とパスワードを指定する．
.TP
.B \-no\-mouse
マウスを利用しない．
.TP
.B \-cookie
クッキーを処理する．
.TP
.B \-no\-cookie
クッキーを処理しない．
.TP
.B \-num
行番号を表示する．
.TP
.B \-dump
URLの内容を読みこみ，整形されたバッファの内容を標準出力に書き出す．
文書の幅は80桁と仮定される．この幅は，次の
.B \-cols
オプションで変更可能．
.TP
.BI \-cols\  幅
.B \-dump
オプションを使う場合に，文書の幅を指定する．
.TP
.BI \-ppc\  ピクセル数
文字の幅を指定する．デフォルトは 8.0．
.TP
.B \-dump_source
URLの内容を読みこみ，整形せずに標準出力に書き出す．漢字コード変換もされない．
.TP
.B \-dump_head
URLにアクセスし，ヘッダ情報を出力する．
.TP
.B \-dump_both
URLにアクセスし，ヘッダ情報とHTMLソースを出力する．
.TP
.B \-dump_extra
URLにアクセスし，拡張情報とヘッダ情報とHTMLソースを出力する．
.TP
.BI \-post\  file
ファイルの内容をPOSTする．
.TP
.BI \-header\  string
HTTP要求ヘッダを追加する．
.TP
.BI \-config\  file
configのファイルを指定する．
.TP
.B -help
ヘルプを表示する.
.TP
.B -version
w3m versionを表示する.
.SS 文書の表示内容
HTML文書を表示しているときには，次のような表示になります．
.in +8n
.TS
box tab(;);
l|c|c
l|c|c
l|c|c
l|c|c.
;カラー表示時;白黒表示時
_
リンク;青色;下線
インライン画像;緑色;反転表示
FORMの入力部分;赤色;反転表示
.TE
.PP
カラー表示時の色は，オプション設定パネル
.B o
で変更することができます．
.SS 起動後の使いかた
起動した後は，1文字のコマンドをキーボードから入力することで
.B w3m
を操作します．
.PP
コマンドには次のようなものがあります．以下の記述では，
.B C-x
はコントロールxを表します．また，
.B SPC
はスペースバー，
.B RET
はリターンキー，
.B ESC
はエスケープキーです．
.PP
ここで書いてあるのは，オリジナル版のキー操作です．
.\" \fIlynx\fr(1)
.\" 風のキー操作用にコンパイルしてあるものについては，
.\" \fIw3m_lynx(1)
.\" をごらんください．
.SS ページ/カーソル移動
.TP 1i
.B SPC, C-v
次のページを表示します．
.TP
.B b, "ESC v"
前のページを表示します．
.TP
.B l, C-f, 右矢印キー
カーソルを右に移動します．
.TP
.B h, C-b, 左矢印キー
カーソルを左に移動します．
.TP
.B j, C-n, 下矢印キー
カーソルを下に移動します．
.TP
.B k, C-p, 上矢印キー
カーソルを上に移動します．
.TP
.B J
画面を1行上にスクロールします．
.TP
.B K
画面を1行下にスクロールします．
.TP
.B ^
行頭に移動します．
.TP
.B $
行末に移動します．
.TP
.B w
次の単語に移動します．
.TP
.B W
前の単語に移動します．
.TP
.B >
画面全体を右にずらします．(表示内容を左にずらす)
.TP
.B <
画面全体を左にずらします．(表示内容を右にずらす)
.TP
.B ". "
画面全体を1文字右にずらします．(表示内容を左にずらす)
.TP
.B ", "
画面全体を1文字左にずらします．(表示内容を右にずらす)
.TP
.B g, M-<
文書のいちばん上の行に移動します．
.TP
.B G, M->
文書のいちばん下の行に移動します．
.TP
.B "ESC g"
画面下で行番号を入力し，そこで指定した行に移動します．
ここで
.$
を入力すると，最終行に移動します．
.TP
.B Z
カーソルのある位置を行の中央に移動します．
.TP
.B z
カーソルのある行を画面の中央に移動します．
.TP
.B TAB
次のリンクに移動します．
.TP
.B C-u, "ESC TAB"
前のリンクに移動します．
.TP
.B [
最初のリンクに移動します．
.TP
.B ]
最後のリンクに移動します．
.SS ハイパーリンク操作
.TP
.B RET
現在カーソルがあるリンクが指す先の文書を読みこみます．
.TP
.B a, "ESC RET"
現在カーソルがあるリンクが指す先の文書をファイルに保存します．
.TP
.B u
現在カーソルがあるリンクが指す先のURLを表示します．
.TP
.B i
リンクに関連付けられた画像へのURLの表示します．
.TP
.B I
現在カーソルがあるリンクに対応する画像を表示します．
.TP
.B "ESC I"
現在カーソルがあるリンクが指す画像をファイルに保存します．
.TP
.B ":"
URL風の文字列をリンクにします．この機能は，HTMLでない文書を
読んでいるときにも有効です．
.TP
.B "ESC :"
Message-ID風の文字列を，news: のリンクにします．この機能は，HTMLでない文書を
読んでいるときにも有効です．
.TP
.B c
現在の文書のURLを表示します．
.TP
.B =
現在の文書に関する情報を表示します．
.TP
.B C-g
ページ中での現在位置を表示します．
.TP
.B C-h
URL履歴を表示します．
.TP
.B F
<FRAMESET>を含む文書を表示しているときに，<FRAME>タグの指す複数の文書を1つの
文書に変換して表示します．
.TP
.B M
現在見ているページを，外部ブラウザを使って表示します．
.B 2M, 3M
で2番目と3番目のブラウザを使います．
.TP
.B "ESC M"
現在のリンク先を，外部ブラウザを使って表示します．
.B "2ESC M", "3ESC M"
で2番目と3番目のブラウザを使います．
.El
.SS ファイルとURL関係の操作
.TP
.B U
URLを指定して開きます．
.TP
.B V
ローカルファイルを指定して開きます．
.TP
.B @
コマンドを実行し，結果を全部読んでから表示します．
.TP
.B #
コマンドを実行し，結果を読みこみながら表示します．
.SS バッファ操作
.TP
.B B
現在見ているバッファを削除し，一つ前のバッファを表示します．
.TP
.B v
HTMLのソースを表示します．
.TP
.B s
バッファ選択モードに入ります．
.TP
.B E
現在見ているバッファがローカルファイルの場合，そのファイルをエディタで編集しま
す．エディタを終了した後，そのファイルを再度読み込みます．
.TP
.B C-l
画面を再描画します．
.TP
.B R
バッファを再度読み込みます．
.TP
.B S
バッファの表示内容をファイルに保存します．
.TP
.B "ESC s"
HTMLのソースをファイルに保存します．
.v
でソースを表示して
.S
で保存するのとほぼ同じですが，
.B "ESC s"
で保存したファイルは漢字コードがオリジナルのままであるのに対して，
.B "v S"
で保存すると現在表示に使っている漢字コードに変換されて保存されます．
.TP
.B "ESC e"
現在表示されているバッファを，表示されている形式のままエディタで編集します．
.SS バッファ選択モード
.B s
でバッファ選択モードに入ったときのキー操作です．
.TP
.B k, C-p
一つ上のバッファを選択します．
.TP
.B j, C-n
一つ下のバッファを選択します．
.TP
.B D
現在選択しているバッファを削除します．
.TP
.B RET
現在選択しているバッファを表示します．
.El
.SS ブックマーク操作
.TP
.B "ESC b"
ブックマークを読み込みます．
.TP
.B "ESC a"
現在見ているページをブックマークに追加します．
.SS 検索
.TP
.B /, C-s
現在のカーソル位置からファイル末尾に向かって正規表現を検索します．
.TP
.B ?,  C-r
現在のカーソル位置からファイルの先頭に向かって正規表現を検索します．
.TP
.B n
次を検索します．
.TP
.B N
前を検索します．
.TP
.B C-w
折り返し検索モードを切り換えます．
.SS マーク操作
.TP
.B C-SPC
マークを設定／解除します．マークは反転表示されます．
.TP
.B "ESC p"
一つ前のマークに移動します．
.TP
.B "ESC n"
一つ後のマークに移動します．
.TP
.B "\""
正規表現で指定された文字列を全てマークします．
.SS その他
.TP
.B !
シェルコマンドを実行します．
.TP
.B H
ヘルプファイルを表示します．
.TP
.B o
オプション設定パネルを表示します．
.TP
.B C-k
クッキー一覧を表示します．
.TP
.B C-c
文書の読み込みを中断します．
.TP
.B C-z
サスペンドします．
.TP
.B q
.B w3m
を終了します．オプションの設定によって，終了するかどうか確認します．
.TP
.B Q
確認せずに
.B w3m
を終了します．
.SS 行編集
画面の最下行で文字列を入力する場合に有効なキー操作です．
.TP
.B C-f
カーソルを右に移動します．
.TP
.B C-b
カーソルを左に移動します．
.TP
.B C-h
カーソルの直前の文字を削除します．
.TP
.B C-d
カーソル位置の文字を削除します．
.TP
.B C-k
カーソル位置から後を削除します．
.TP
.B C-u
カーソル位置から前を削除します．
.TP
.B C-a
文字列の先頭に移動します．
.TP
.B C-e
文字列の最後に移動します．
.TP
.B C-p
ヒストリから一つ前の文字列を取り出します．
.TP
.B C-n
ヒストリから次の文字列を取り出します．
.TP
.B TAB, SPC
ファイル名入力時に，ファイル名を補完します．
.TP
.B RET
入力を終了します．
.SH SEE ALSO
.I kterm\fR(1),
.\" .I lynx\fR(1),
.\" .I w3m_lynx\fR(1),
.I tty\fR(4)
.SH AUTHOR
伊藤 彰則
.br
aito@fw.ipsj.or.jp

