.nr N -1
.nr D 5
.TH W3M 1 Local
.UC 4
.SH NAME
w3m \- a text based Web browser and pager
.SH SYNOPSIS
.B w3m
[options] [URL or filename]
.PP
.SH DESCRIPTION
.\" This defines appropriate quote strings for nroff and troff
.ds lq \&"
.ds rq \&"
.if t .ds lq ``
.if t .ds rq ''
.\" Just in case these number registers aren't set yet...
.if \nN==0 .nr N 10
.if \nD==0 .nr D 5
.I
w3m
is a World Wide Web (WWW) text based client. It has English and
Japanese help files and an option menu and can be configured to
use either language. It will display hypertext markup language
(HTML) documents containing links to files residing on the local
system, as well as files residing on remote systems. It can
display HTML tables and frames.
In addition, it can be used as a "pager" in much the same manner
as "more" or "less".
Current versions of
.I
w3m
run on
Unix (Solaris, SunOS, HP-UX, Linux, FreeBSD, and EWS4800)
and on
Microsoft Windows 9x/NT.
.PP
.SH OPTIONS
At start up, \fIw3m\fR will load any local
file or remote URL specified at the command
line.  For help with runtime options, press \fB"H"\fR
while running \fIw3m\fR.
Command line options are:
.PP
.TP
.B -t tab
set tab width
.TP
.B -r
ignore backspace effect
.TP
.B -l line
# of preserved line (default 10000)
.TP
.B -I charset
document charset
.TP
.B -O charset
display/output charset
.TP
.B -B
load bookmark
.TP
.B -bookmark file
specify bookmark file
.TP
.B -T type
specify content-type
.TP
.B -m
internet message mode
.TP
.B -v
visual startup mode
.TP
.B -M
monochrome display
.TP
.B -N
distribute multiple command line arguments to tabs. By default, a
stack of buffers is used
.TP
.B -F
automatically render frame
.TP
.B -dump
dump formatted page into stdout
.TP
.B -cols num
with stdout as destination; HTML is rendered to lines of \fInum\fR characters
.TP
.B -ppc count
specify the number of pixels per character (4.0...32.0).
Larger values will make tables narrower.  [default 8.0]
.TP
.B -ppl count
specify the number of pixels per line (4.0...64.0)
.TP
.B -dump_source
dump page source into stdout
.TP
.B -dump_head
dump response of HEAD request into stdout
.TP
.B -dump_both
dump HEAD and source into stdout
.TP
.B -dump_extra
dump HEAD, source, and extra information into stdout
.TP
.B -post file
use POST method with file content
.TP
.B -header string
insert string as a header
.TP
.B +<num>
goto <num> line
.TP
.B -num
show line number
.TP
.B -no-proxy
don't use proxy
.TP
.B -4
IPv4 only (-o dns_order=4)
.TP
.B -6
IPv6 only (-o dns_order=6)
.TP
.B -no-mouse
don't use mouse
.TP
.B -cookie
use cookie.
.TP
.B -no-cookie
don't use cookie
.TP
.B -graph
use graphic character
.TP
.B -no-graph
don't use graphic character
.TP
.B -s
squeeze multiple blank lines
.TP
.B -W
toggle wrap search mode
.TP
.B -X
don't use termcap init/deinit
.TP
.B -title [=TERM]
set buffer name to terminal title string. 
If TERM is specified, use the TERM style title configuration.
.TP
.B -o option=value
modify one configuration item with an explicitly given value; without \fIoption=value\fR, equivalent to -show-option
.TP
.B -show-option
show all available config option
.TP
.B -config file
specify config file
.TP
.B -help
show usage
.TP
.B -version
show w3m version
.TP
.B -reqlog
write request logfile
.TP
.B -debug
DO NOT USE
.SH EXAMPLES
.SS Pager-like usage 
.TP
Combine snippets of HTML code and preview the page 
.EX
$ cat header.html footer.html | w3m -T text/html
.EE
.TP
Compare two files using tabs 
.EX
$ w3m -N config.old config
.EE
.SS Browser-like usage 
.TP
Display web content in monochrome terminal
.EX
$ w3m -M http://w3m.sourceforge.net
.EE
.TP
Display embedded graphics
.EX
$ w3m -o auto_image=TRUE http://w3m.sourceforge.net
.EE
.TP
Display content from Usenet  
.EX
$ w3m -m nntp://news.aioe.org/comp.os.linux.networking
.EE
.TP
Upload data for a URL using the POST method 
.EX
$ w3m -post - http://example.com/form.php <<<'a=0&b=1'
.EE
.SS Filter-like usage
.TP
Convert an HTML file to plain text with a defined line length
.EX
$ w3m -cols 40 foo.html > foo.txt
.EE
.TP
Output the bookmarks page as text with an appended list of links
.EX
$ w3m -B -o display_link_number=1 > out.txt
.EE
.TP
Conversion of file format and character encoding
.EX
$ w3m -T text/html -I EUC-JP -O UTF-8 < foo.html > foo.txt
.EE
.SS Start with no input
.TP
Welcome users with a built-in page
.EX
$ w3m -v
.EE
.SH FILES
.TP
\f(CW~/.w3m/bookmark.html\fP
default bookmark file 
.TP
\f(CW~/.w3m/config\fP
user defined configuration file; overrides \f(CW/etc/w3m/config\fP
.TP
\f(CW~/.w3m/cookie\fP
cookie jar; written on exit, read on launch   
.TP
\f(CW~/.w3m/history\fP
browser history - visited files and URLs
.TP
\f(CW~/.w3m/keymap\fP
user defined key bindings; overrides default key bindings
.TP
\f(CW~/.w3m/mailcap\fP
external viewer configuration file
.TP
\f(CW~/.w3m/menu\fP
user defined menu; overrides default menu
.TP
\f(CW~/.w3m/mime.types\fP
MIME types file
.TP
\f(CW~/.w3m/mouse\fP
user defined mouse settings
.TP
\f(CW~/.w3m/passwd\fP
password and username file
.TP
\f(CW~/.w3m/pre_form\fP
contains predefined values to fill recurrent HTML forms
.\" .TP
.\" .I $~/.w3m/urimethodmap
.\" ???
.SH NOTES
This is the
.I
w3m
0.5.3 Release.
.PP
Please see the MANUAL.html file distributed with w3m for
more detailed documentation.

Additional information about
.I
w3m
may be found on its Japanese language Web site located at:
  http://w3m.sourceforge.net/index.ja.html
.br
or on its English version of the site at:
  http://w3m.sourceforge.net/index.en.html
.SH ACKNOWLEDGMENTS
.I
w3m
has incorporated code from several sources.
Users have contributed patches and suggestions over time.
.SH AUTHOR
Akinori ITO <aito@fw.ipsj.or.jp>
