#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
        update-alternatives --quiet --remove pager /usr/bin/w3m
	update-alternatives --quiet --remove www-browser /usr/bin/w3m
        ;;
    *)
esac

#DEBHELPER#
