.TH W3M 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
w3m \- WWW wo Miru Tool, WWW browsing Tool
.SH SYNOPSIS
.B w3m
.I "[options] [files or URL] ..."
.br
.SH "DESCRIPTION"
This manual page documents briefly the
.BR w3m
commands.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.\" Instead, it has documentation in the GNU Info format; see below.
.PP
.B w3m
is a program that browse text files, and also browse WWW pages.
.SH OPTIONS
A summary of options are included below.
.\" For a complete description, see the Info files.
.TP
.B \-h
Show summary of options.
.TP
.B \-t [tab]
set tab width
.TP
.B \-r
Ignore backspace effect
.TP
.B \-l [line]
# of preserved line (default 10000)
.\" disabled in debian
.\" .TP
.\" .B \-s
.\" Shift_JIS
\." .TP
.\" .B \-j
.\" JIS
.\" .TP
.\" .B \-e
.\" EUC-JP
.TP
.B \-B
load bookmark
.TP
.B \-T [type]
specify content-type
.TP
.B \-m
internet message mode
.TP
.B \-v
visual startup mode
.TP
.B \-M
monochrome display
.TP
.B \-F
automatically render frame
.TP
.B \-dump
dump formatted page into stdout
.TP
.B \-cols [width]
specify column width (used with -dump)
.TP
.B \-ppc [count]
specify the number of pixels per character (4.0...32.0)
.TP
.B \-dump_source
dump page source into stdout
.TP
.B \-dump_head
dump response of HEAD request into stdout
.TP
.B +[num]
goto <num> line
.TP
.B \-num
show line number
.TP
.B \-no-proxy
don't use proxy
.TP
.B \-no-mouse
don't use mouse
.TP
.B \-cookie
use cookie
.TP
.B \-no-cookie
don't use cookie
.TP
.B \-s
squeeze multiple blank lines
.TP
.B \-W
toggle wrap search mode
.TP
.B \-X
don't use termcap init/deinit
.TP
.B \-o [opt]=[value]
assign value to config option
.TP
.B \-config [file]
specify config file
.SH "SEE ALSO"
You can see keymaps by pressing `H' key while browsing
or /usr/share/w3m/w3mhelp.html.
Also, there are some documents in /usr/share/doc/w3m but it is
written in Japanese.
.SH AUTHOR
This manual page was written by Fumitoshi UKAI <ukai@debian.or.jp>,
for the Debian GNU/Linux system (but may be used by others).
